name: Report an issue
description: Create a bug report to fix an issue
title: "Issue: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: >
        :warning: **Please do not report security vulnerabilities here**

        Be careful with sensitive information and security vulnerabilities. In order to report bugs that could contain
        sensitive information, use [Launchpad](https://bugs.launchpad.net/ubuntu/+source/ubuntu-insights/+filebug) instead.
        For security vulnerabilities, see our [security policy](https://github.com/ubuntu/ubuntu-insights/security).
        On Ubuntu machines, you can use `ubuntu-bug ubuntu-insights` to collect relevant information.


        Thanks for taking the time to report an issue and help improve Ubuntu Insights! Please fill out the form below as
        best as you can so that we can help you.


        Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general
        support or usage questions, use [Ubuntu Discourse](https://discourse.ubuntu.com/c/desktop/8).


        By submitting an Issue to this repository, you agree to the terms within the
        [Ubuntu Code of Conduct](https://ubuntu.com/community/code-of-conduct).
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      options:
        - label: I have searched the existing issues and found none that matched mine
          required: true
  - type: textarea
    attributes:
      label: Describe the issue
      description: >
        Provide a clear and concise description of what the issue is, including what you expected to happen.
        Please include what the triggering source was if applicable (CLI, systemd, libraries, etc.)
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: >
        Detail the steps taken to reproduce this error, what was expected, and whether this issue can be reproduced
        consistently or if it is intermittent.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...

        Please include screenshots (you can drag any image here) where applicable. Redact any sensitive information.
    validations:
      required: true
  - type: textarea
    attributes:
      label: "System information and logs"
      description: |
        Please include all relevant system information and logs that can help us diagnose the issue, including consent configuration files.

        To get debug output from the CLI, run the command with the `-vv` flag.

        For library or bindings bugs, get the logs by setting the appropriate log level through the API.

        By default, consent configuration files are located in:
        - `~/.config/ubuntu-insights/` on Linux systems
        - `~/Library/Application Support/ubuntu-insights/` on macOS systems
        - `%appdata%\ubuntu-insights\` on Windows systems

        If this bug report pertains to the Ubuntu `ubuntu-insights` package, you may copy and paste the following command to make collection of relevant information easier. It will open a text editor with the system information, relevant logs, and consent configuration files. Paste the output below. Redact any sensitive information from the output.
        ```bash
        sudo -v
        TMPFILE=$(mktemp ubuntu-insights-system-info-XXXXXX.md)
        if command -v xdg-open > /dev/null && [ -n "${DISPLAY:-}" ]; then insights_editor=xdg-open; elif [ -n "${EDITOR:-}" ]; then insights_editor="$EDITOR"; fi
        cat > "$TMPFILE" <<EOF && ${insights_editor:-editor} "$TMPFILE"
        #### ubuntu-insights version
        \`\`\`
        $(/usr/bin/ubuntu-insights --version)
        \`\`\`

        #### Distribution
        \`\`\`
        $(lsb_release -a)
        \`\`\`

        #### Systemd Collect Logs
        \`\`\`
        $(journalctl --user -u ubuntu-insights-collect.service -u ubuntu-insights-collect.timer -n 1000 -o short-monotonic)
        \`\`\`

        #### Systemd Upload Logs
        \`\`\`
        $(journalctl --user -u ubuntu-insights-upload.service -u ubuntu-insights-upload.timer -n 1000 -o short-monotonic)
        \`\`\`

        #### ubuntu-insights apt history
        \`\`\`
        $(awk -v RS= -v ORS="\n\n" '/ubuntu-insights/' /var/log/apt/history.log)
        \`\`\`

        #### Default consent configuration folder contents
        \`\`\`
        $(if [ -d "$HOME/.config/ubuntu-insights" ]; then
          find "$HOME/.config/ubuntu-insights" -type f | while read -r file; do
            echo "----- $file -----"
            cat "$file"
            echo
          done
        else
          echo "No ~/.config/ubuntu-insights directory found."
        fi)
        \`\`\`
        EOF
        ```
      placeholder: >
        Paste your system info and logs here. Redact any sensitive information.
  - type: textarea
    attributes:
      label: Relevant information
      description: >
        Please look at our
        [Ubuntu Insights Troubleshooting guide](../#troubleshooting)
        and provide the debug logs for Ubuntu Insights.

      placeholder: Remember to redact any sensitive information from them.
  - type: checkboxes
    attributes:
      label: Double check your logs
      options:
        - label: I have redacted any sensitive information from the logs
          required: true
