/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 4 "libinsights.go"

#include "types.h"
#include <stdlib.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif


/**
 * insights_collect creates a report for the specified source.
 * If config is NULL, defaults are used.
 * source may be NULL or "" to use platform default.
 * flags may be NULL.
 * If collection fails, an error string is returned.
 * Otherwise, this returns NULL.
 *
 * If out_report is not NULL,
 * the pretty printed report is returned in out_report
 * as a null-terminated C string.
 * Note that this return may not match with what is written
 * to disk depending on provided flags and the consent state.
 * If the consent state is determined to be false, an OptOut report
 * will be written to disk, but the full compiled report will still be returned.
 *
 * The out_report must be freed by the caller.
 * The error string must be freed.
 **/
extern char* insights_collect(insights_const_config* config, insights_const_char* source, insights_const_collect_flags* flags, char** out_report);

/**
 * insights_compile compiles the report for the specified source.
 * If config is NULL, defaults are used.
 * If "flags" is NULL, defaults are used.
 * If compilation fails, an error string is returned.
 * Otherwise, this returns NULL.
 *
 * If out_report is not NULL, the pretty printed report is
 * returned via out_report as a null-terminated C string.
 *
 * The out_report must be freed by the caller.
 * The error string must be freed.
 **/
extern char* insights_compile(insights_const_config* config, insights_const_compile_flags* flags, char** out_report);

/**
 * insights_write writes the report to disk based on the consent state.
 * If config is NULL, defaults are used.
 * If "source" is NULL or "" the platform default is used.
 * If "report" is not a valid Insights report, an error string is returned.
 * If "flags" is NULL, defaults are used.
 * If writing fails, an error string is returned.
 * Any error string returned must be freed.
 **/
extern char* insights_write(insights_const_config* config, insights_const_char* source, insights_const_char* report, insights_const_write_flags* flags);

/**
 * insights_upload uploads reports for the specified sources.
 * If config is NULL, defaults are used.
 * sources may be NULL or empty to handle all reports.
 * sourcesLen is the number of sources in the array.
 * flags may be NULL.
 * If uploading fails, an error string is returned.
 * Otherwise, this returns NULL.
 * The error string must be freed.
 **/
extern char* insights_upload(insights_const_config* config, insights_const_char** sources, size_t sources_len, insights_const_upload_flags* flags);

/**
 * insights_get_consent_state gets the consent state for the specified source.
 * If config is NULL, defaults are used.
 * source may be NULL or "" to retrieve the default consent state.
 * If it could not be retrieved, this function returns CONSENT_UNKNOWN.
 * Otherwise, it returns the consent state of the source.
 **/
extern insights_consent_state insights_get_consent_state(insights_const_config* config, insights_const_char* source);

/**
 * insights_set_consent_state sets the state for the specified source to newState.
 * If config is NULL, defaults are used.
 * source may be NULL or "" to affect the default consent state.
 * If the state could not be set, this function returns an error string.
 * Otherwise, it returns NULL
 * The error string must be freed.
 **/
extern char* insights_set_consent_state(insights_const_config* config, insights_const_char* source, _Bool new_state);

/**
 * insights_set_log_callback sets the callback function for logging.
 * The callback receives the log level and the null terminated message.
 * Setting the callback overrides the default logging behavior.
 * Pass NULL to reset to default behavior.
 *
 * The callback may be called concurrently from multiple threads.
 * The implementation must be thread-safe.
 */
extern void insights_set_log_callback(insights_logger_callback callback);

#ifdef __cplusplus
}
#endif
