name: Prepare environment for CI
description: Prepare the environment for CI by preparing and installing common dependencies.

inputs:
  working-directory:
    description: Directory where the action is ran. All other paths are relative to this one. The `go.work` file is expected to be in this directory.
    default: "."
  apt-dependencies:
    description: A space-separated list of apt dependencies to install (Ignored if not using a Linux runner).
    default: ""
  download-go-deps:
    description: Whether to pre-download Go module dependencies for all modules in the repository.
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: ${{ inputs.working-directory }}/go.work
        cache-dependency-path: |
          ${{ inputs.working-directory }}/insights/go.sum
          ${{ inputs.working-directory }}/server/go.sum
          ${{ inputs.working-directory }}/common/go.sum
          ${{ inputs.working-directory }}/tools/go.sum

    - name: Install dependencies on Linux
      if: runner.os == 'Linux' && inputs.apt-dependencies != ''
      shell: bash
      run: |
        set -e
        sudo apt-get update
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y ${{ inputs.apt-dependencies }}

    - name: Download Go module dependencies
      if: inputs.download-go-deps == 'true'
      shell: bash
      run: |
        set -euo pipefail
        cd ${{ inputs.working-directory }}
        find . -type f -name 'go.mod' -print0 | while IFS= read -r -d '' file; do
          dir=$(dirname "$file")
          echo "Downloading Go module dependencies in $dir"
          (cd "$dir" && go mod download)
        done
