name: Prepare environment for CI
description: Prepare the environment for CI by preparing and installing common dependencies.

inputs:
  go-version-file:
    description: Path to a Go version file (go.mod, go.work) to determine the Go version to install.
    default: "go.work"
  apt-dependencies:
    description: A space-separated list of apt dependencies to install (Ignored if not using a Linux runner).
    default: ""
  download-go-deps:
    description: Whether to pre-download Go module dependencies for all modules in the repository.
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: ${{ inputs.go-version-file }}
        cache-dependency-path: |
          insights/go.sum
          server/go.sum
          common/go.sum
          tools/go.sum

    - name: Install dependencies on Linux
      if: runner.os == 'Linux' && inputs.apt-dependencies != ''
      shell: bash
      run: |
        set -e
        sudo apt-get update
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y ${{ inputs.apt-dependencies }}

    - name: Download Go module dependencies
      if: inputs.download-go-deps == 'true'
      shell: bash
      run: |
        set -euo pipefail
        find . -type f -name 'go.mod' -print0 | while IFS= read -r -d '' file; do
          dir=$(dirname "$file")
          echo "Downloading Go module dependencies in $dir"
          (cd "$dir" && go mod download)
        done

    - name: Generate shared libraries
      shell: bash
      run: |
        set -euo pipefail
        go generate insights/C/generate.go
